defmodule FleetPrompt.Repo.TenantMigrations.FixAgentState do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:agents, prefix: prefix()) do
      remove :status
    end
  end

  def down do
    alter table(:agents, prefix: prefix()) do
      add :status, :text, default: "draft"
    end
  end
end
