defmodule FleetPrompt.Repo.TenantMigrations.AddCoreResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE EXTENSION IF NOT EXISTS \"pgcrypto\"")

    create_if_not_exists table(:agents, primary_key: false, prefix: prefix()) do
      add(:id, :uuid,
        null: false,
        default: fragment("public.gen_random_uuid()"),
        primary_key: true
      )

      add(:name, :text, null: false)
      add(:description, :text)
      add(:version, :text, default: "1.0.0")
      add(:status, :text, default: "draft")
      add(:config, :map)
      add(:system_prompt, :text, null: false)
      add(:max_concurrent_requests, :bigint, default: 5)
      add(:timeout_seconds, :bigint, default: 30)
      add(:total_executions, :bigint, default: 0)
      add(:total_tokens_used, :bigint, default: 0)
      add(:avg_latency_ms, :bigint)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:state, :text, null: false, default: "draft")
    end
  end

  def down do
    drop_if_exists(table(:agents, prefix: prefix()))
  end
end
